import React from 'react';
import Category from '~/layouts/Category';
import Footer from '~/layouts/Footer';
import Header from '~/layouts/Header';

const items = {
    food: [
        {
            id: 1001,
            name: 'bánh canh ghẹ nhỏ',
            oldPrice: 55000,
            newPrice: 45000,
            size: 'nhỏ',
            description: 'ăn ngon vl',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667639406/MMFood/Food/banh-canh-nho_w4rtvf.jpg',
        },
        {
            id: 1002,
            name: 'bánh canh ghẹ vừa',
            oldPrice: 65000,
            newPrice: 55000,
            size: 'vừa',
            description: 'ngon vl',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667639889/MMFood/Food/banh-canh-to_wdkjoc.jpg',
        },
        {
            id: 1003,
            name: 'bánh canh ghẹ (đặt biệt)',
            oldPrice: 85000,
            newPrice: 75000,
            size: 'vừa',
            description: 'ngon vl',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667639893/MMFood/Food/banh-canh-dacbiet_nkjhsy.jpg',
        },
        {
            id: 1004,
            name: 'bánh canh ghẹ nguyên con',
            oldPrice: 60000,
            newPrice: 50000,
            size: 'vừa',
            description: 'ngon vl',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667641431/MMFood/Food/banh-canh-ghe_p5aucl.webp',
        },
        {
            id: 1005,
            name: 'chả cá lăng (set 2 người)',
            oldPrice: 149000,
            newPrice: 139000,
            size: 'to',
            description: 'ngon vl',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667639897/MMFood/Food/cha-calang-2-4_m6txfb.jpg',
        },
        {
            id: 1006,
            name: 'chả cá lăng (set 4 người) ',
            oldPrice: 299000,
            newPrice: 279000,
            size: 'to',
            description: 'ngon vl',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667639898/MMFood/Food/cha-calang-4-6_glrxoa.jpg',
        },
        {
            id: 1007,
            name: 'bánh mì chảo bít tết (sốt tiêu đen) ',
            oldPrice: 99000,
            newPrice: 89000,
            size: 'vừa',
            description: 'ngon vl',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667639901/MMFood/Food/banhmi-sot-tieu_rxlxzr.jpg',
        },
    ],
    drink: [
        {
            id: 2001,
            name: 'trà tắc sài gòn',
            oldPrice: 19000,
            newPrice: 19000,
            size: 'vừa',
            description: 'ngon vắt lưỡi',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667640607/MMFood/Drink/tratac-sg_vuxn7c.jpg',
        },
        {
            id: 2002,
            name: 'trà tắc sài nha đam',
            oldPrice: 25000,
            newPrice: 25000,
            size: 'to',
            description: 'ngon vắt lưỡi',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667640605/MMFood/Drink/pepsi_z2w5fi.jpg',
        },
        {
            id: 2003,
            name: 'trà đào',
            oldPrice: 39000,
            newPrice: 39000,
            size: 'to',
            description: 'ngon vắt lưỡi',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667640591/MMFood/Drink/tra-dao_rksyns.jpg',
        },
        {
            id: 2004,
            name: "trà sữa trân châu M'M",
            oldPrice: 35000,
            newPrice: 35000,
            size: 'vừa',
            description: 'ngon vắt lưỡi',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667640606/MMFood/Drink/trasua-tranchau_lcaggq.jpg',
        },
        {
            id: 2005,
            name: 'trà sữa trân châu đường đen',
            oldPrice: 35000,
            newPrice: 35000,
            size: 'vừa',
            description: 'ngon vắt lưỡi',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667640593/MMFood/Drink/tranchau-duongden_igihkw.jpg',
        },
        {
            id: 2006,
            name: 'nước suối',
            oldPrice: 10000,
            newPrice: 10000,
            size: 'nhỏ',
            description: 'ngon vắt lưỡi',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667640584/MMFood/Drink/nuoc-suoi_acnndh.jpg',
        },
        {
            id: 2007,
            name: 'pepsi',
            oldPrice: 15000,
            newPrice: 15000,
            size: 'nhỏ',
            description: 'ngon vắt lưỡi',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667640605/MMFood/Drink/pepsi_z2w5fi.jpg',
        },
        {
            id: 2008,
            name: 'bia SG',
            oldPrice: 25000,
            newPrice: 25000,
            size: 'vừa',
            description: 'ngon vắt lưỡi',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667640567/MMFood/Drink/biaSg_h6smih.jpg',
        },
        {
            id: 2009,
            name: 'bia Strong Bow táo',
            oldPrice: 30000,
            newPrice: 30000,
            size: 'vừa',
            description: 'ngon vắt lưỡi',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667640588/MMFood/Drink/strong-bow-tao_mjdxwp.png',
        },
        {
            id: 2010,
            name: 'bia Strong Bow dâu',
            oldPrice: 30000,
            newPrice: 30000,
            size: 'vừa',
            description: 'ngon vắt lưỡi',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667640586/MMFood/Drink/strong-bow-dau_a8gpjn.jpg',
        },
    ],
    hotpot: [
        {
            id: 3001,
            name: 'set lẩu 2 ngăn size vừa (2-3 người)',
            oldPrice: 199000,
            newPrice: 190000,
            size: 'vừa',
            description: 'ngon vắt lưỡi',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667641310/MMFood/Hotpot/lau-2-nguoi_urclwh.jpg',
        },
        {
            id: 3002,
            name: 'set lẩu 2 ngăn size Lớn (4-6 người)',
            oldPrice: 399000,
            newPrice: 390000,
            size: 'lớn',
            description: 'ngon vắt lưỡi',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667641314/MMFood/Hotpot/lau-4-nguoi_qtaui5.jpg',
        },
    ],
    extra: [
        {
            id: 4001,
            name: 'bò lẩu thêm',
            oldPrice: 80000,
            newPrice: 80000,
            size: 'vừa',
            description: 'ngon vắt lưỡi',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667640915/MMFood/Extra/bo-tha-lau_b7dppv.jpg',
        },
        {
            id: 4002,
            name: 'nạm bò thêm',
            oldPrice: 99000,
            newPrice: 99000,
            size: 'vừa',
            description: 'ngon vắt lưỡi',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667640909/MMFood/Extra/nam-bo-them_o8kph0.jpg',
        },
        {
            id: 4003,
            name: 'rau lẩu thêm',
            oldPrice: 25000,
            newPrice: 25000,
            size: 'vừa',
            description: 'ngon vắt lưỡi',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667640910/MMFood/Extra/rau-lau-them_yoxan2.jpg',
        },
        {
            id: 4004,
            name: 'nấm lẩu thêm',
            oldPrice: 40000,
            newPrice: 40000,
            size: 'vừa',
            description: 'ngon vắt lưỡi',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667640909/MMFood/Extra/nam-tha-lau_zw9w5h.jpg',
        },
    ],
    topping: [
        {
            id: 5001,
            name: 'quẩy sài gòn',
            oldPrice: 10000,
            newPrice: 10000,
            size: 'to',
            description: 'ngon vắt lưỡi',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667641215/MMFood/Toping/quay_zcx5wk.jpg',
        },
        {
            id: 5002,
            name: 'bún thêm',
            oldPrice: 10000,
            newPrice: 10000,
            size: 'nhỏ',
            description: 'ngon vắt lưỡi',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667641212/MMFood/Toping/bun-them_ak4fwt.jpg',
        },
        {
            id: 5003,
            name: 'rau chả cá thêm',
            oldPrice: 20000,
            newPrice: 20000,
            size: 'vừa',
            description: 'ngon vắt lưỡi',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667641212/MMFood/Toping/rau-cha-ca_mi1wkg.jpg',
        },
        {
            id: 5004,
            name: 'bao tử cá thêm',
            oldPrice: 55000,
            newPrice: 55000,
            size: 'to',
            description: 'ngon vắt lưỡi',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667641212/MMFood/Toping/bao-tu-ca_xpvzq2.jpg',
        },
        {
            id: 5005,
            name: ' cá lăng thêm',
            oldPrice: 85000,
            newPrice: 85000,
            size: 'to',
            description: 'ngon vắt lưỡi',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667641211/MMFood/Toping/ca-lang_nma7hn.jpg',
        },
        {
            id: 5006,
            name: 'ghẹ nguyên con',
            oldPrice: 50000,
            newPrice: 50000,
            size: 'to',
            description: 'ngon vắt lưỡi',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667641214/MMFood/Toping/Ghe-nguyen-con_bux3qn.jpg',
        },
        {
            id: 5007,
            name: 'lạc rang',
            oldPrice: 10000,
            newPrice: 10000,
            size: 'nhỏ',
            description: 'ngon vắt lưỡi',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667641212/MMFood/Toping/rau-cha-ca_mi1wkg.jpg',
        },
        {
            id: 5008,
            name: 'bánh mì thêm',
            oldPrice: 5000,
            newPrice: 5000,
            size: 'vừa',
            description: 'ngon vắt lưỡi',
            url: 'https://res.cloudinary.com/dqhuy/image/upload/v1667641211/MMFood/Toping/banh-mi_a7vysn.jpg',
        },
    ],
};
class Topping extends React.Component {
    state = {};
    render() {
        return (
            <>
                <Header />
                <Category data={items.topping} />
                <Footer />
            </>
        );
    }
}

export default Topping;
